### ISSUE TITLE
Find free alternatives to fonts used in the original client

### ISSUE THREAD

**Issue by broxen** [Segs/Segs-Data#1]
Some of the tools we make might want to follow the original graphical style, so we need replacements for the following fonts:
- [ ] fonts/mont_hvbold.ttf -> "Montreal-Heavy, Regular"
- [ ] fonts/mont_demibold.ttf -> "Montreal-DemiBold, Regular"
- [ ] fonts/REDCIRCL.ttf -> "Red Circle, Regular"
- [ ] fonts/tahomab.ttf -> "Tahoma, Bold"
- [ ] fonts/verdana*.ttf
- [ ] fonts/cour.ttf "Courier New"
- [ ] fonts/digitalb.ttf "Digital-Bold, Thin"

@mobbyg has compiled most of these.

**Comment by mobbyg** [comment]
Posted file, and created a wiki page showing replacements.
